spring:
    profiles:
    active:
    - dev
---
spring:
    profiles: dev
    application:
        name: microservicecloud-config-student01-dev
---
spring:
    profiles: test
    application:
        name: microservicecloud-config-student01-test